### ISSUE TITLE
OSError: PortAudio library not found

### ISSUE THREAD

**Issue by sanderjo** [n1teshy/py-listener#1]
```
git clone https://github.com/n1teshy/py-listener.git
cd py-listener/
python3 -m venv venv
venv/bin/python3 -m pip install py-listener
```

Then, with the example from Basic Usage

```
sander@zwarte:~/git/py-listener$ venv/bin/python3 testje.py 
Traceback (most recent call last):
  File "/home/sander/git/py-listener/testje.py", line 1, in <module>
    from listener import Listener
  File "/home/sander/git/py-listener/listener/__init__.py", line 1, in <module>
    from listener.core import Listener
  File "/home/sander/git/py-listener/listener/core.py", line 9, in <module>
    import sounddevice as sd
  File "/home/sander/git/py-listener/venv/lib/python3.12/site-packages/sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found

```

**Comment by n1teshy** [comment]
I think you are on a linux platform, a lot of python libraries rely on portaudio for sound I/O, try installing portaudio, https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/scripts/readme-gen/templates/install_portaudio.tmpl.rst.

**Comment by sanderjo** [comment]
Yes, Ubuntu.

Solved with

`sudo apt install portaudio19-dev`
