### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/sander/.cache/whisper/small.pt'

### ISSUE THREAD

**Issue by sanderjo** [n1teshy/py-listener#2]
```
sander@zwarte:~/git/py-listener$ venv/bin/python3 testje.py 
Traceback (most recent call last):
  File "/home/sander/git/py-listener/testje.py", line 5, in <module>
    listener = Listener(speech_handler=print)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sander/git/py-listener/listener/core.py", line 220, in __init__
    download_whisper_model(self.whisper_size)
  File "/home/sander/git/py-listener/listener/core.py", line 70, in download_whisper_model
    with urllib.request.urlopen(url) as source, open(
                                                ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/sander/.cache/whisper/small.pt'

```

There is no such directory:

```
sander@zwarte:~/git/py-listener$ ll /home/sander/.cache/whisper/
ls: cannot access '/home/sander/.cache/whisper/': No such file or directory
```

Something else I need to install?

**Comment by n1teshy** [comment]
This is most likely a bug, I'm on it.

**Comment by n1teshy** [comment]
Hi @sanderjo , this issue has been fixed and tested on ubuntu-20 and windows 10, the version 0.1.3 has the fix and some other fixes too.

**Comment by sanderjo** [comment]
Confirmed! I can now run the example script ... but nothing happens. So an example script to actually listens & converts to text would be nice.

**Comment by n1teshy** [comment]
Nothing happens? is it not printing what you say? or did you mean an example that shows something useful being done with what you said?

**Comment by sanderjo** [comment]
Nothing happens.

I start talking, I start the app up, I keep talking, and it quits. Nothing but the below.

But maybe I'm using the wrong code? See below.

```
sander@zwarte:~/git/py-listener$ time venv/bin/python3 testje.py 
/home/sander/git/py-listener/venv/lib/python3.12/site-packages/whisper/__init__.py:150: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fp, map_location=device)
Using cache found in /home/sander/.cache/torch/hub/snakers4_silero-vad_master

real	0m6.152s
user	0m5.111s
sys	0m1.395s
```



This is the code I use:
```
from listener import Listener

# prints what the speaker is saying, look at all
# parameters of the constructor to find out more features
listener = Listener(speech_handler=print)

# start listening
listener.listen()

# NOTE: listening is done from a separate thread, so you must
# have other operations to keep the interpreter going, or it will
# quit. if your code has no other operations, just run a loop like
# below.

# --------------------
# import time

# while True:
#     time.sleep(1)
# -----------------------

# stops listening
listener.stop()

# starts listening again
# listener.listen()

```

**Comment by n1teshy** [comment]
in the given exmaple, it says 

NOTE: listening is done from a separate thread, so you must
have other operations to keep the interpreter going, or it will
quit. if your code has no other operations, just run a loop like
below.

you're supposed to uncomment the while loop, or you can run it in a jupyter notebook and you wouldn't have to run that loop.

this tool runs in a separate thread as to not block the interpreter, do you want an option to listen in the main thread, that might block the interpreter but it'll be simpler to use.

**Comment by sanderjo** [comment]
WOW! It's working. It even understands Dutch, and spells it correctly ("gebeurt" vs "gebeurd"). Fascinating! 

It's quite slow. One sentence per 30 seconds or so ... or ... a sentence is printed after 15 seconds ... not sure.

Would a Hailo 8 improve this? Or is CUDA the only way to go?

Impressive work, @n1teshy 




```
 the car is driving
 car is driving around
 You can stop now.
 Kijk, de dingen die ik zei, die komen in beeld.
 We kijken televisie.


 We gaan kijken wat er gebeurt.
 We gaan kijken wat er gebeurt. Het is in een ver verleden gebeurd.
```

**Comment by n1teshy** [comment]
Thank you, a lot of the credit belongs to [openai-whisper](https://github.com/openai/whisper)

I don't know much about Hailo 8, google says it offers 26 TFLOPS so it should be significantly faster than a CPU, I ran this same script on an intel i5 and it ran fine for short sentences like the ones in your message, it ran with 5-10 second delays, it's much better on CUDA though, I used NVIDIA RTX 3050, a 'very' consumer grade GPU. Are you selecting a large model with the `whisper_size` option?

**Comment by sanderjo** [comment]
> Are you selecting a large model with the `whisper_size` option?

I just run the example code ... and I see no whisper_size ?

(Note: I know about nothing about AI Programming)

**Comment by n1teshy** [comment]
You can choose a size for the underlying whisper model through the `whisper_size` parameter of the `Listener` class, it's automatically selected if you don't, `small` is selected on CPU environments because that's the one I've found to be reasonable on CPUs in my experience, you can pass `tiny`, or `tiny.en` if you're only going to speak english, and the latency will reduce at the cost of quality, bigger model ~= better quality, also, being in a quiet place and speaking close to the mic helps with the quality.

`listener = Listener(speech_handler=print, whisper_size="small")`

`listener = Listener(speech_handler=print, whisper_size="small.en") # english only`

or you can pass `base` or `base.en`, `small > base > tiny` for both size and quality.

**Comment by sanderjo** [comment]
> listener = Listener(speech_handler=print, whisper_size="small.en") # english only

Thanks.

It downloaded 461MB, and now it only speaks English.

Cool.
